# Generated by Django 5.2.7 on 2025-11-17 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified')], default='Interested', max_length=20)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('bullet', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('Used', 'Used'), ('New', 'New')], max_length=10)),
                ('km', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('price_adquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('integration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.CharField(choices=[('Test Drive', 'Test Drive'), ('In progress', 'In progress'), ('Closed', 'Closed')], default='', max_length=20)),
                ('selling_date', models.DateField(blank=True, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GDMFX.leads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_sold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GDMFX.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='leads',
            name='interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GDMFX.vehicles'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('id_document', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sign_date', models.DateField(null=True)),
                ('received', models.DateField(null=True)),
                ('file_pdf', models.FileField(null=True, upload_to='contracts/')),
                ('customer_type', models.CharField(choices=[('Customer', 'Customer'), ('Business', 'Business')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_sold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GDMFX.vehicles')),
            ],
        ),
    ]
