# Generated by Django 5.0.1 on 2025-11-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDMFX', '0002_alter_sales_selling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='selling_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
