# Generated by Django 5.0.1 on 2025-11-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDMFX', '0003_alter_sales_selling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Business', 'Business')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id_document',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='phase',
            field=models.CharField(choices=[('Test Drive', 'Test Drive'), ('In progress', 'In progress'), ('Closed', 'Closed')], default='Test Drive', max_length=20),
        ),
    ]
