# Generated by Django 6.0.1 on 2026-02-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDMFX', '0005_meets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meets',
            old_name='customer_name',
            new_name='name',
        ),
    ]
