# Generated by Django 6.0.2 on 2026-03-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDMFX', '0008_userprofile_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
