# Generated by Django 6.0.2 on 2026-03-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDMFX', '0009_userprofile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
